### ISSUE TITLE
Code Snippets in the Cloud - wrapping links

### ISSUE THREAD

**Issue by paaljoachim** [codesnippetspro/codesnippets.cloud#1]
Hey

I noticed this after adding a few links in the description.
https://codesnippets.cloud/snippet/Easy%20Web%20Design%20Tutorials/Stop%20success%20email%20of%20plugin%20auto%20update.

![Screenshot 2022-10-10 at 14 11 47](https://user-images.githubusercontent.com/5323259/194863644-75445092-707f-46fd-8837-1bd05f9c359c.jpg)

**Comment by lightbulbman** [comment]
Hey @paaljoachim Thanks for sharing this and please be reassured this will be fixed in the next minor update coming within next 2 weeks.
